### ISSUE TITLE
ASCII banner has no graphics

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [dekz/dcrypt#4]

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
Please refer to projects such as https://github.com/jashkenas/coffee-script and https://github.com/mauricemach/zappa as well as https://github.com/feisty/requisition for the appropriate use of graphics in ASCII banners

**Comment by dekz** [comment]
Working as intended
