### ISSUE TITLE
optional ECDSA

### ISSUE THREAD

**Issue by donpark** [dekz/dcrypt#5]
OpenSSL RPMs are often built with ECDSA disabled, causing dcrypt build to fail. It would be nice if ECDSA feature was optional.

**Comment by dekz** [comment]
Will take a look when I once again have the internet

**Comment by dekz** [comment]
Give the latest a try
    node-waf configure --without-ecdsa=true
    node-waf build

**Comment by donpark** [comment]
yes, that works great. when I get some time, I'll see if there is a way to turn the flag on automatically at build time when ecdsa.h is missing so npm install will work on systems w/o ECDSA enabled OpenSSL.

**Comment by donpark** [comment]
K, got it. Adding the following script to `wscript`'s `configure` function will disable ECDSA if `openssl/ecdsa.h` file is missing.

```
if not conf.check(header_name='openssl/ecdsa.h', compile_mode='cxx'):
  conf.env["WITHOUT_ECDSA"] = True
  conf.env.append_value("CXXFLAGS", "-DWITH_ECDSA=0")
```

**Comment by donpark** [comment]
filed a formal pull request with a variation of above change. closing this issue.
